(* ::Package:: *)

(* ::Input:: *)
(*(*\!\(\**)
(*TagBox[*)
(*RowBox[{*)
(*RowBox[{"(", "\[NoBreak]", *)
(*TagBox[GridBox[{*)
(*{"gammas"},*)
(*{*)
(*RowBox[{"-", *)
(*FractionBox[*)
(*RowBox[{*)
(*RowBox[{*)
(*RowBox[{"-", "2"}], " ", "betao", " ", "CO2", " ", "gammao", " ", "k", " ", *)
(*RowBox[{"pico", "[", "x", "]"}], " ", *)
(*RowBox[{"pido", "[", "x", "]"}]}], "+", *)
(*RowBox[{*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"2", " ", "betao", " ", "CO2", " ", "gammao", " ", "k"}], "-", *)
(*RowBox[{"gammao", " ", "k", " ", "no"}], "+", *)
(*RowBox[{"no", " ", "r", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"crit", " ", "k"}], "-", *)
(*RowBox[{"2", " ", *)
(*RowBox[{"(", *)
(*RowBox[{"crit", "+", "k"}], ")"}], " ", "x"}], "+", *)
(*RowBox[{"3", " ", *)
(*SuperscriptBox["x", "2"]}]}], ")"}]}], "+", *)
(*RowBox[{"k", " ", "no", " ", *)
(*RowBox[{"Eff", "[", *)
(*RowBox[{"x", ",", "0", ",", "CO2"}], "]"}]}]}], ")"}], " ", *)
(*SuperscriptBox[*)
(*RowBox[{"pido", "[", "x", "]"}], "2"]}], "+", *)
(*SqrtBox[*)
(*RowBox[{*)
(*SuperscriptBox[*)
(*RowBox[{"pido", "[", "x", "]"}], "2"], " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{*)
(*RowBox[{"-", "2"}], " ", "betao", " ", "CO2", " ", "gammao", " ", "k", " ", *)
(*RowBox[{"pico", "[", "x", "]"}]}], "+", *)
(*RowBox[{*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"2", " ", "betao", " ", "CO2", " ", "gammao", " ", "k"}], "-", *)
(*RowBox[{"gammao", " ", "k", " ", "no"}], "+", *)
(*RowBox[{"no", " ", "r", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"crit", " ", "k"}], "-", *)
(*RowBox[{"2", " ", *)
(*RowBox[{"(", *)
(*RowBox[{"crit", "+", "k"}], ")"}], " ", "x"}], "+", *)
(*RowBox[{"3", " ", *)
(*SuperscriptBox["x", "2"]}]}], ")"}]}], "+", *)
(*RowBox[{"k", " ", "no", " ", *)
(*RowBox[{"Eff", "[", *)
(*RowBox[{"x", ",", "0", ",", "CO2"}], "]"}]}]}], ")"}], " ", *)
(*RowBox[{"pido", "[", "x", "]"}]}]}], ")"}], "2"], "+", *)
(*RowBox[{"4", " ", "k", " ", "no", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"betao", " ", "CO2", " ", "k", " ", "no", " ", "qo", " ", "x", " ", *)
(*RowBox[{"Dpido", "[", "x", "]"}], " ", *)
(*RowBox[{"(", *)
(*RowBox[{"eco", "-", *)
(*RowBox[{"edo", "[", "x", "]"}]}], ")"}], " ", *)
(*RowBox[{"pico", "[", "x", "]"}]}], "+", *)
(*RowBox[{*)
(*RowBox[{"pido", "[", "x", "]"}], " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"betao", " ", "CO2", " ", "k", " ", "no", " ", "qo", " ", "x", " ", *)
(*RowBox[{"Dpico", "[", "x", "]"}], " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"-", "eco"}], "+", *)
(*RowBox[{"edo", "[", "x", "]"}]}], ")"}]}], "+", *)
(*RowBox[{"gammao", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"r", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"crit", " ", "k"}], "-", *)
(*RowBox[{"2", " ", *)
(*RowBox[{"(", *)
(*RowBox[{"crit", "+", "k"}], ")"}], " ", "x"}], "+", *)
(*RowBox[{"3", " ", *)
(*SuperscriptBox["x", "2"]}]}], ")"}]}], "+", *)
(*RowBox[{"k", " ", *)
(*RowBox[{"Eff", "[", *)
(*RowBox[{"x", ",", "0", ",", "CO2"}], "]"}]}]}], ")"}], " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"2", " ", "betao", " ", "CO2", " ", *)
(*RowBox[{"pico", "[", "x", "]"}]}], "+", *)
(*RowBox[{*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{*)
(*RowBox[{"-", "2"}], " ", "betao", " ", "CO2"}], "+", "no"}], ")"}], " ", *)
(*RowBox[{"pido", "[", "x", "]"}]}]}], ")"}]}]}], ")"}]}]}], ")"}]}]}], ")"}]}]]}], *)
(*RowBox[{"2", " ", "k", " ", "no", " ", *)
(*SuperscriptBox[*)
(*RowBox[{"pido", "[", "x", "]"}], "2"]}]]}]},*)
(*{*)
(*FractionBox[*)
(*RowBox[{*)
(*RowBox[{"2", " ", "betao", " ", "CO2", " ", "gammao", " ", "k", " ", *)
(*RowBox[{"pico", "[", "x", "]"}], " ", *)
(*RowBox[{"pido", "[", "x", "]"}]}], "-", *)
(*RowBox[{*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"2", " ", "betao", " ", "CO2", " ", "gammao", " ", "k"}], "-", *)
(*RowBox[{"gammao", " ", "k", " ", "no"}], "+", *)
(*RowBox[{"no", " ", "r", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"crit", " ", "k"}], "-", *)
(*RowBox[{"2", " ", *)
(*RowBox[{"(", *)
(*RowBox[{"crit", "+", "k"}], ")"}], " ", "x"}], "+", *)
(*RowBox[{"3", " ", *)
(*SuperscriptBox["x", "2"]}]}], ")"}]}], "+", *)
(*RowBox[{"k", " ", "no", " ", *)
(*RowBox[{"Eff", "[", *)
(*RowBox[{"x", ",", "0", ",", "CO2"}], "]"}]}]}], ")"}], " ", *)
(*SuperscriptBox[*)
(*RowBox[{"pido", "[", "x", "]"}], "2"]}], "+", *)
(*SqrtBox[*)
(*RowBox[{*)
(*SuperscriptBox[*)
(*RowBox[{"pido", "[", "x", "]"}], "2"], " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*SuperscriptBox[*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{*)
(*RowBox[{"-", "2"}], " ", "betao", " ", "CO2", " ", "gammao", " ", "k", " ", *)
(*RowBox[{"pico", "[", "x", "]"}]}], "+", *)
(*RowBox[{*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"2", " ", "betao", " ", "CO2", " ", "gammao", " ", "k"}], "-", *)
(*RowBox[{"gammao", " ", "k", " ", "no"}], "+", *)
(*RowBox[{"no", " ", "r", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"crit", " ", "k"}], "-", *)
(*RowBox[{"2", " ", *)
(*RowBox[{"(", *)
(*RowBox[{"crit", "+", "k"}], ")"}], " ", "x"}], "+", *)
(*RowBox[{"3", " ", *)
(*SuperscriptBox["x", "2"]}]}], ")"}]}], "+", *)
(*RowBox[{"k", " ", "no", " ", *)
(*RowBox[{"Eff", "[", *)
(*RowBox[{"x", ",", "0", ",", "CO2"}], "]"}]}]}], ")"}], " ", *)
(*RowBox[{"pido", "[", "x", "]"}]}]}], ")"}], "2"], "+", *)
(*RowBox[{"4", " ", "k", " ", "no", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"betao", " ", "CO2", " ", "k", " ", "no", " ", "qo", " ", "x", " ", *)
(*RowBox[{"Dpido", "[", "x", "]"}], " ", *)
(*RowBox[{"(", *)
(*RowBox[{"eco", "-", *)
(*RowBox[{"edo", "[", "x", "]"}]}], ")"}], " ", *)
(*RowBox[{"pico", "[", "x", "]"}]}], "+", *)
(*RowBox[{*)
(*RowBox[{"pido", "[", "x", "]"}], " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"betao", " ", "CO2", " ", "k", " ", "no", " ", "qo", " ", "x", " ", *)
(*RowBox[{"Dpico", "[", "x", "]"}], " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"-", "eco"}], "+", *)
(*RowBox[{"edo", "[", "x", "]"}]}], ")"}]}], "+", *)
(*RowBox[{"gammao", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"r", " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"crit", " ", "k"}], "-", *)
(*RowBox[{"2", " ", *)
(*RowBox[{"(", *)
(*RowBox[{"crit", "+", "k"}], ")"}], " ", "x"}], "+", *)
(*RowBox[{"3", " ", *)
(*SuperscriptBox["x", "2"]}]}], ")"}]}], "+", *)
(*RowBox[{"k", " ", *)
(*RowBox[{"Eff", "[", *)
(*RowBox[{"x", ",", "0", ",", "CO2"}], "]"}]}]}], ")"}], " ", *)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{"2", " ", "betao", " ", "CO2", " ", *)
(*RowBox[{"pico", "[", "x", "]"}]}], "+", *)
(*RowBox[{*)
(*RowBox[{"(", *)
(*RowBox[{*)
(*RowBox[{*)
(*RowBox[{"-", "2"}], " ", "betao", " ", "CO2"}], "+", "no"}], ")"}], " ", *)
(*RowBox[{"pido", "[", "x", "]"}]}]}], ")"}]}]}], ")"}]}]}], ")"}]}]}], ")"}]}]]}], *)
(*RowBox[{"2", " ", "k", " ", "no", " ", *)
(*SuperscriptBox[*)
(*RowBox[{"pido", "[", "x", "]"}], "2"]}]]}*)
(*},*)
(*GridBoxAlignment->{"Columns" -> {{Center}}, "ColumnsIndexed" -> {}, "Rows" -> {{Baseline}}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}},*)
(*GridBoxSpacings->{"Columns" -> {Offset[0.27999999999999997`], {Offset[0.5599999999999999]}, Offset[0.27999999999999997`]}, "ColumnsIndexed" -> {}, "Rows" -> {Offset[0.2], {Offset[0.4]}, Offset[0.2]}, "RowsIndexed" -> {}, "Items" -> {}, "ItemsIndexed" -> {}}],*)
(*Column], "\[NoBreak]", ")"}], "*)"}],*)
(*Function[BoxForm`e$, MatrixForm[BoxForm`e$]]]\)*)


(* ::Input:: *)
(**)
(*trueVanilla = {r->0.2,k->10,crit->0.1,ns->100,no->100,ps->5000,po->5000,qs->0.007,qo->0.007,ws->1,wo->1,ms->1,mo->1,ehats->0.6,ehato->0.6,gammas->0.1,gammao->0.1,betas->0.2,betao->0.2,a->-0.3,b->0.1102};*)
(**)
(*(*Derivative of OMNRF defector profit.*)*)
(*Dpido[x]=po*ehato/.trueVanilla;*)
(**)
(*(*edo[x] Check = 0.05714285714285715 < x for our constraints in both cases.*)*)
(*(wo+mo)/(po*qo)/.trueVanilla;*)
(**)
(*(*Derivative of OMNRF coop profit.*)*)
(*Dpico[x]=po*eco/.trueVanilla;*)
(**)
(*(*OMNRF defector profit.*)*)
(*pido[x]=po*qo*ehato*x-wo*ehato/.trueVanilla;*)
(**)
(*(*OMNRF Defector Effort*)*)
(*edo[x]=ehato;*)
(**)
(*(*OMNRF coop profit.*)*)
(*pico[x]=po*qo*eco*x-wo*eco+mo*(ehato-eco)/.trueVanilla;*)
(**)
(*(*Eff(x,0,co2)*)*)
(*Eff[x,0,CO2]=qs*ehats*ns+qo*(ehato(no-CO2)+eco*CO2)/.trueVanilla*)
(**)
(*(*CO2*)*)
(*CO2=no*((-betao/gammao)*(1-(pico[x]/pido[x]))+1)/.trueVanilla*)
(**)
(**)
(**)


(* ::Input:: *)
(**)
(*-(1/(2 k no pido[x]^2))(-2 betao CO2 gammao k pico[x] pido[x]+(2 betao CO2 gammao k-gammao k no+no r (crit k-2 (crit+k) x+3 x^2)+k no Eff[x,0,CO2]) pido[x]^2+\[Sqrt](pido[x]^2 ((-2 betao CO2 gammao k pico[x]+(2 betao CO2 gammao k-gammao k no+no r (crit k-2 (crit+k) x+3 x^2)+k no Eff[x,0,CO2]) pido[x])^2+4 k no (betao CO2 k no qo x Dpido[x] (eco-edo[x]) pico[x]+pido[x] (betao CO2 k no qo x Dpico[x] (-eco+edo[x])+gammao (r (crit k-2 (crit+k) x+3 x^2)+k Eff[x,0,CO2]) (2 betao CO2 pico[x]+(-2 betao CO2+no) pido[x]))))))/.trueVanilla*)
(**)
(*1/(2 k no pido[x]^2) (2 betao CO2 gammao k pico[x] pido[x]-(2 betao CO2 gammao k-gammao k no+no r (crit k-2 (crit+k) x+3 x^2)+k no Eff[x,0,CO2]) pido[x]^2+\[Sqrt](pido[x]^2 ((-2 betao CO2 gammao k pico[x]+(2 betao CO2 gammao k-gammao k no+no r (crit k-2 (crit+k) x+3 x^2)+k no Eff[x,0,CO2]) pido[x])^2+4 k no (betao CO2 k no qo x Dpido[x] (eco-edo[x]) pico[x]+pido[x] (betao CO2 k no qo x Dpico[x] (-eco+edo[x])+gammao (r (crit k-2 (crit+k) x+3 x^2)+k Eff[x,0,CO2]) (2 betao CO2 pico[x]+(-2 betao CO2+no) pido[x]))))))/.trueVanilla*)


(* ::Input:: *)
(**)


(* ::Input:: *)
(**)


(* ::Input:: *)
(*Plot3D[-(1/(2000 (-0.6`+ 21.` x)^2))(-40.` (-0.6`+ 21.` x) (0.6` -2 eco+35.` eco x) (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+(-0.6`+ 21.` x)^2 (-100.`+ 20.` (1.` -20.2` x+3 x^2)+40.` (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+1000 (0.42` +0.007` (100 eco (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+0.6` (100-100 (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))))))+\[Sqrt]((-0.6`+ 21.` x)^2 ((-40.` (0.6` -2 eco+35.` eco x) (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+(-0.6`+ 21.` x) (-100.`+ 20.` (1.` -20.2` x+3 x^2)+40.` (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+1000 (0.42` +0.007` (100 eco (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+0.6` (100-100 (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x))))))))^2+4000 (420000.00000000006` (-0.6`+eco) x (0.6` -2 eco+35.` eco x) (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+(-0.6`+ 21.` x) (700000.0000000001` (0.6` -eco) eco x (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+0.1` (40.` (0.6` -2 eco+35.` eco x) (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+(-0.6`+ 21.` x) (100-40.` (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x))))) (0.2` (1.` -20.2` x+3 x^2)+10 (0.42` +0.007` (100 eco (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+0.6` (100-100 (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x))))))))))))*)
(*/.trueVanilla,{x,((ehats-a)/b),k}/.trueVanilla,{eco,0,0.6},AxesLabel->{Subscript[SuperStar[x], 2],Subscript[(e^C), o][t],Subscript[\[Lambda], 1]},PlotLabel->"Graph of \!\(\*SubscriptBox[\(\[Lambda]\), \(1\)]\)(\!\(\*SubscriptBox[SuperscriptBox[\(x\), \(*\)], \(2\)]\)(t),0,\!\(\*SubscriptBox[SuperscriptBox[\(C\), \(*\)], SubscriptBox[\(o\), \(2\)]]\)) versus Real \!\(\*SubscriptBox[SuperscriptBox[\(x\), \(*\)], \(2\)]\)(t) and OMNRF Cooperator Effort from 0 to 0.6"]*)
(**)
(*Plot3D[1/(2000 (-0.6`+ 21.` x)^2) (40.` (-0.6`+ 21.` x) (0.6` -2 eco+35.` eco x) (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))-(-0.6`+ 21.` x)^2 (-100.`+ 20.` (1.` -20.2` x+3 x^2)+40.` (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+1000 (0.42` +0.007` (100 eco (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+0.6` (100-100 (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))))))+\[Sqrt]((-0.6`+ 21.` x)^2 ((-40.` (0.6` -2 eco+35.` eco x) (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+(-0.6`+ 21.` x) (-100.`+ 20.` (1.` -20.2` x+3 x^2)+40.` (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+1000 (0.42` +0.007` (100 eco (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+0.6` (100-100 (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x))))))))^2+4000 (420000.00000000006` (-0.6`+eco) x (0.6` -2 eco+35.` eco x) (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+(-0.6`+ 21.` x) (700000.0000000001` (0.6` -eco) eco x (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+0.1` (40.` (0.6` -2 eco+35.` eco x) (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+(-0.6`+ 21.` x) (100-40.` (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x))))) (0.2` (1.` -20.2` x+3 x^2)+10 (0.42` +0.007` (100 eco (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x)))+0.6` (100-100 (1-2.` (1-(0.6` -2 eco+35.` eco x)/(-0.6`+ 21.` x))))))))))))*)
(*/.trueVanilla,{x,((ehats-a)/b),k}/.trueVanilla,{eco,0,0.6},AxesLabel->{Subscript[SuperStar[x], 2],Subscript[(e^C), o][t],Subscript[\[Lambda], 3]},PlotLabel->"Graph of \!\(\*SubscriptBox[\(\[Lambda]\), \(3\)]\)(\!\(\*SubscriptBox[SuperscriptBox[\(x\), \(*\)], \(2\)]\)(t),0,\!\(\*SubscriptBox[SuperscriptBox[\(C\), \(*\)], SubscriptBox[\(o\), \(2\)]]\)) versus Real \!\(\*SubscriptBox[SuperscriptBox[\(x\), \(*\)], \(2\)]\)(t) and OMNRF Cooperator Effort from 0 to 0.6"]*)



